-- MySQL Script generated by MySQL Workbench
-- Mon May 25 13:55:08 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema timetracking
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema timetracking
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `timetracking` DEFAULT CHARACTER SET utf8 ;
USE `timetracking` ;

-- -----------------------------------------------------
-- Table `timetracking`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timetracking`.`user` ;

CREATE TABLE IF NOT EXISTS `timetracking`.`user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(45) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `timetracking`.`activities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timetracking`.`activities` ;

CREATE TABLE IF NOT EXISTS `timetracking`.`activities` (
  `idactivity` BIGINT NOT NULL AUTO_INCREMENT,
  `duration` BIGINT NULL,
  `goal` VARCHAR(255) NULL,
  `name` VARCHAR(45) NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idactivity`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `timetracking`.`request`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timetracking`.`request` ;

CREATE TABLE IF NOT EXISTS `timetracking`.`request` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `action` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `user_id` BIGINT NOT NULL,
  `activity_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_request_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_request_activities1_idx` (`activity_id` ASC) VISIBLE,
  CONSTRAINT `fk_request_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `timetracking`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_request_activities1`
    FOREIGN KEY (`activity_id`)
    REFERENCES `timetracking`.`activities` (`idactivity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `timetracking`.`user_has_activities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timetracking`.`user_has_activities` ;

CREATE TABLE IF NOT EXISTS `timetracking`.`user_has_activities` (
  `user_id` BIGINT NOT NULL,
  `activities_id` BIGINT NOT NULL,
  PRIMARY KEY (`user_id`, `activities_id`),
  INDEX `fk_user_has_activities_activities1_idx` (`activities_id` ASC) VISIBLE,
  INDEX `fk_user_has_activities_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_activities_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `timetracking`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_activities_activities1`
    FOREIGN KEY (`activities_id`)
    REFERENCES `timetracking`.`activities` (`idactivity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `timetracking`.`activities_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timetracking`.`activities_history` ;

CREATE TABLE IF NOT EXISTS `timetracking`.`activities_history` (
  `idactivity` BIGINT NOT NULL,
  `duration` BIGINT NULL,
  `goal` VARCHAR(255) NULL,
  `name` VARCHAR(45) NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idactivity`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
